apiVersion: v1
kind: Service
metadata:
  name: episode4backend-service
spec:
  type: NodePort
  selector:
    app: episode4backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 4000
      nodePort: 30006
