apiVersion: v1
kind: Service
metadata:
  name: episode4frontend-service
spec:
  type: NodePort
  selector:
    app: episode4frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30007
